### ISSUE TITLE
I think the switch to fusebase broke something.

### ISSUE THREAD

**Issue by alsoeric** [thecodrr/nimbus-note-exporter#2]
when I run the exporter, I get:

> alsoeric@juno:~/fb-recovery$ nimbus-note-exporter 
> ? Your Nimbus Note email: › (node:69448) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> ✔ Your Nimbus Note email: … ###########
> ✔ Your Nimbus Note password: … ****************
> ✔ Logged in as portal.in3x.io
> ✔ Found 1 organizations
> ✔ Found 5 workspaces
> ✔ Found 86 folders across 5 workspaces
> ✔ Found 676 notes across 5 workspaces
> ✔ 676 downloaded.
> ✔ Notes processed.
> ✔ All done.

but I only get 61 note files out of nimbus-notes-exporter.  any ideas?

thanks!

**Comment by ichnichtich** [comment]
I've just tried the script with the same result: Found 1342 notes across 2 workspace but only 52 notes in the zip file. Seems like the script is not working any more. :(

Any chance that someone fixes this?

**Comment by thecodrr** [comment]
The script requests the notes in batches and waits for Fusebase to respond. If Fusebase doesn't respond within 60 seconds, it skips the note.

**Comment by hubekraven** [comment]
@thecodrr,  
Hey there, 
first of all I love your initiative to help retrive/exports our notes from FuseBase as there is no acceptable feature on that regard from their part... But as others have stated above, the downloaded files don't match the result of findings by the script

✔ Found 1 organizations
✔ Found 4 workspaces
✔ Found 14 folders across 4 workspaces
✔ Found 340 notes across 4 workspaces
✔ 340 downloaded.    
✔ Notes processed.
✔ All done.

But I have only 60 notes actually returned in the zip files.
Any idea how to fixe that ? Also where can we get the fuse Base API doc if any?   
Again thanks for your work. very nice start

**Comment by SargeMadovsky** [comment]
Hi, thanks for your work, it is much appreciated.
I have the same situation, the script finds 1842 notes but only 102 folders in the final archive.
Ready to make a donation for finalizing the plugin if possible.

**Comment by hubekraven** [comment]
> The script requests the notes in batches and waits for Fusebase to respond. If Fusebase doesn't respond within 60 seconds, it skips the note.

I have noticed that increasing the timeout to above 2/3 second increases the output of the downloaded files. With a timeout 5 mins my returned folders when up to 100 in zip from 60 folders in the previous attempt... But I am not sure if it realistic to timeout above 10 min .

**Comment by thecodrr** [comment]
I think Nimbus rate limits after a certain amount of requests per hour/minute. Not sure of the exact amount but that is my guess. I can add some basic throttling and see how it goes.

**Comment by thecodrr** [comment]
Even in the app if you request too many exports it stops responding.

**Comment by thecodrr** [comment]
@hubekraven can you try exporting from their old desktop app which had export capabilities and see if all your notes export?

**Comment by SargeMadovsky** [comment]
> @hubekraven can you try exporting from their old desktop app which had export capabilities and see if all your notes export?

As I see it, the old application creates a full offline standalone json-DB on C:\Users\[USER]\AppData\Roaming\nimbus-electron\databases\[NUMBER].
It has tags, dates and other meta.
Just need a converter or some kind of parser to merge metadata and attachments to make them ready to import into other applications.

**Comment by Semsoid** [comment]
> @hubekraven can you try exporting from their old desktop app which had export capabilities and see if all your notes export?

The desktop app still produces a full export for me.

**Comment by palashman** [comment]
### FYI about official nimbusnote-offline.exe

Official https://nimbusweb.me/nimbusnote-offline.exe successfully exported **almost** all notes (I precisely counted them).

Limitations of official exe I met: 
* It can not properly export old editor notes with attachments. So you have to convert those notes to new format at first.
* Also there were a few random notes it could not be able to export. Those notes can be exported with Nimbus web client (one by one).

**Comment by palashman** [comment]
Could you advice?
The script says "Error: Wrong password", although account and password are correct.

---
**My steps**
I just installed `node-v20.19.4-x64.msi` (with NPM). 
Command `>npm -v` shows 10.8.2
Command `>node -v` shows 20.19.4

Then I run `npm i -g nimbus-note-exporter`
Then `nimbus-note-exporter`, it asks for email and password. 
```
√ Your Nimbus Note email: ... mybox11@gmail.com
√ Your Nimbus Note password: ... ****************
/ Logging you in...C:\Users\user11\AppData\Roaming\npm\node_modules\nimbus-note-exporter\dist\api\auth.js:41
            throw new Error("Wrong password.");
                  ^

Error: Wrong password.
    at C:\Users\user11\AppData\Roaming\npm\node_modules\nimbus-note-exporter\dist\api\auth.js:41:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user11\AppData\Roaming\npm\node_modules\nimbus-note-exporter\dist\api\auth.js:23:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.19.4
```

---
**The only difference** in output between this script and nimbusnote-offline.exe is **`metadata.json`**, isn't it? 
Is there any script that can use this json to help move your Nimbus stuff to Obsidian Markdown?

**Comment by hubekraven** [comment]
[palashman](https://github.com/palashman)
Same here can no longer connect to the account through the app

**Comment by palashman** [comment]
Lets take a look on the problem from another view point.

Using mentioned **`nimbusnote-offline.exe`** for bunch and **web client** for some individual notes I exported all notes. How to get tags, and maybe human names for attachments?

I figured out that folder `AppData\Roaming\nimbus-electron\` (used by `nimbusnote-offline.exe`) contains some sort of text databases. How to pull this data from there and how to put it in notes?
